### ISSUE TITLE
error:0308010C:digital

### ISSUE THREAD

**Issue by richardHaggioGwati** [PacktPublishing/React-Material-UI-Cookbook#11]
I am trying to use the code in conjunction with the book but after running
```
npm install
`````
they are 50 vulnerabilities (30 moderate, 20 high) which prevent me from running storybook and even after running 
```
npm audit fix --force
```
I am still unable to run storybook

Error log
```
info @storybook/react v6.1.21
info
info => Loading static files from C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\public and serving at /.
info => Loading custom manager config
info => Loading presets
info => Loading presets
info => Loading 1 config file in "./.storybook"
(node:10544) DeprecationWarning: Configuration files such as "config", "presets" and "addons" are deprecated and will be removed in Storybook 7.0.
Read more about it in the migration guide: https://github.com/storybookjs/storybook/blob/master/MIGRATION.md#to-mainjs-configuration
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading custom manager config
WARN Storybook support for Create React App is now a separate preset.
WARN To use the new preset, install `@storybook/preset-create-react-app` and add it to the list of `addons` in your `.storybook/main.js` config file.
WARN The built-in preset has been disabled in Storybook 6.0.
info => Using default Webpack setup
10% building 1/4 modules 3 active C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\@storybook\core\dist\server\preview\globals.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\NTCHO\Desktop\Code\React-Material-UI-Cookbook\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by jgruber** [comment]
export NODE_OPTIONS=--openssl-legacy-provider
npm run storybook

Problem with webpack and OpenSSL
